name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # Assurez-vous de spécifier la version de Python appropriée
  - pip
  - pip:

    - cv==1.0.0
    - cycler==0.12.1
    - einops==0.8.0

    - matplotlib==3.9.1
    - matplotlib-inline==0.1.7

    - mpmath==1.3.0
    - nest_asyncio==1.6.0
    - networkx==3.3
    - numpy==1.26.4
    - nx==0.0.0
    - opencv-python==4.10.0.84
    - packaging==24.1

    - pillow==10.3.0
    - pip==24.0
  
    - scipy==1.14.0

    - stack-data==0.6.2
    - sympy==1.12
    - torch==2.3.1
    - torchaudio==2.3.1
    - torchdiffeq==0.2.4
    - torchvision==0.18.1
    - ipykernel==6.29.5
    - ipython==8.27.0
    - wandb==0.17.4

