wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722333379.684993
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.9.19
      5: 0.15.4
      8:
      - 5
